### ISSUE TITLE
No route to host

### ISSUE THREAD

**Issue by TonyStarkn** [3ndG4me/AutoBlue-MS17-010#50]
After doin every steps perfectly, i come up with this error "No route to host". What is the solution for this??

**Comment by 3ndG4me** [comment]
Hey there. Usually that means that your system cannot fully reach or connect to the target system's services or IP address. This could be for a wide range of reasons. I'd start by trying to ping your target or running and nmap scan on port 445 to see if the host and the target service can even be reached. 

Ultimately without more information I cannot determine if this is a tool issue or not. More importantly if you do have issues in the future please include screenshots of the errors your seeing and and the exact commands you're running. This could very well be a valid issue somehow but it is impossible to know based on your description.

Even running a "ping" or another tool could give you the exact an error and it is unhelpful in diagnosing the issue. I'll close this issue for now, and suggest you open a new one with more details if you still encounter a problem in the future.
